# Generated by Django 2.0.5 on 2019-01-02 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
                ('middle_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('fathers_name', models.CharField(max_length=20)),
                ('mother_name', models.CharField(max_length=20)),
                ('present_address', models.CharField(max_length=30)),
                ('permanent_address', models.CharField(max_length=20)),
                ('house_no', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('street', models.CharField(max_length=20)),
                ('thana', models.CharField(max_length=20)),
                ('district', models.CharField(max_length=20)),
                ('post_code', models.CharField(max_length=20)),
                ('date_of_birth', models.DateField(max_length=8)),
                ('previous_club_name', models.CharField(max_length=20)),
                ('fromm', models.CharField(max_length=20)),
                ('to', models.CharField(max_length=20)),
                ('total_runs', models.CharField(max_length=20)),
                ('total_wickets', models.CharField(max_length=20)),
                ('team_leader', models.CharField(max_length=20)),
                ('best_performance_club_name', models.CharField(max_length=20)),
                ('opponent_club_name', models.CharField(max_length=20)),
                ('event_id', models.IntegerField()),
                ('match_id', models.IntegerField()),
                ('runs', models.IntegerField()),
                ('wickets', models.IntegerField()),
                ('name_of_degree', models.CharField(max_length=20)),
                ('institution', models.CharField(max_length=20)),
                ('board', models.CharField(max_length=20)),
                ('passing_year', models.IntegerField()),
                ('result', models.CharField(max_length=10)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('membership', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cricketclubinformation.Membership')),
            ],
        ),
    ]
