# Generated by Django 2.0.5 on 2019-01-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricketclubinformation', '0002_auto_20190102_0852'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.IntegerField()),
                ('club_name', models.CharField(blank=True, max_length=20, null=True)),
                ('first_name', models.CharField(blank=True, max_length=20, null=True)),
                ('middle_name', models.CharField(blank=True, max_length=20, null=True)),
                ('last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('player_id', models.IntegerField()),
                ('authorized_Person_first_name', models.CharField(max_length=20)),
                ('authorized_Person_middle_name', models.CharField(blank=True, max_length=20, null=True)),
                ('authorized_Person_last_name', models.CharField(blank=True, max_length=20, null=True)),
                ('designation', models.CharField(blank=True, max_length=20, null=True)),
                ('contract_period_start_date', models.DateTimeField()),
                ('contract_period_end_date', models.DateField()),
                ('contract_amount', models.IntegerField()),
                ('payment_serial_number', models.IntegerField()),
                ('payment_due_date', models.DateField()),
                ('payment_date', models.DateField()),
                ('payment_amount', models.IntegerField()),
                ('contract_witness', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
