# Generated by Django 2.0.5 on 2019-01-02 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricketclubinformation', '0005_clubregistratoin'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayersPerformance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_id', models.IntegerField(blank=True, null=True)),
                ('venue_id', models.IntegerField(blank=True, null=True)),
                ('date_of_the_match', models.DateField(blank=True, null=True)),
                ('player_id', models.IntegerField(blank=True, null=True)),
                ('total_wickets', models.IntegerField(blank=True, null=True)),
                ('total_runs', models.IntegerField(blank=True, null=True)),
                ('out_standing_performance', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
