# Generated by Django 2.0.5 on 2019-01-02 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricketclubinformation', '0006_playersperformance'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.IntegerField(blank=True, null=True)),
                ('venue_id', models.IntegerField(blank=True, null=True)),
                ('date_of_the_match', models.DateField(blank=True, null=True)),
                ('match_id', models.IntegerField(blank=True, null=True)),
                ('man_of_the_match', models.CharField(blank=True, max_length=20, null=True)),
                ('umpires', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
