# Generated by Django 2.0.5 on 2019-01-02 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricketclubinformation', '0007_matchinformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('club_id', models.IntegerField(blank=True, null=True)),
                ('player_id', models.IntegerField(blank=True, null=True)),
                ('team_formation_date', models.DateField(blank=True, null=True)),
                ('event_id', models.IntegerField(blank=True, null=True)),
                ('team_leader_id', models.IntegerField(blank=True, null=True)),
                ('team_ledar_name', models.CharField(blank=True, max_length=20, null=True)),
                ('coach_id', models.IntegerField(blank=True, null=True)),
                ('coach_name', models.CharField(blank=True, max_length=20, null=True)),
                ('playr_id', models.IntegerField(blank=True, null=True)),
                ('player_name', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
