# Generated by Django 2.0.5 on 2019-01-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cricketclubinformation', '0008_teaminformation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerregistration',
            name='event_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerregistration',
            name='first_name',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='playerregistration',
            name='match_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerregistration',
            name='passing_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerregistration',
            name='runs',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerregistration',
            name='wickets',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
